services:
  proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: taohash-proxy
    volumes:
      - ../config:/app/config
    ports:
      - "${PROXY_PORT:-3331}:3331"
      - "${PROXY_PORT_HIGH:-3332}:3332"
      - "${DASHBOARD_PORT:-5000}:5000"
      - "${RELOAD_API_PORT:-5001}:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - CLICKHOUSE_REQUIRED=false
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-clickhouse}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-taohash123}
    restart: unless-stopped
    depends_on:
      - clickhouse

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: taohash-api
    entrypoint: ["python", "-m", "uvicorn"]
    command: ["src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "${API_PORT:-8888}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - API_TOKENS=${API_TOKENS}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-clickhouse}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8123}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-taohash123}
    restart: unless-stopped
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: taohash-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-taohash123}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  clickhouse_data:
    driver: local